import { makeRestaurantStub } from './restaurant-stub';

export function makeRoleStub() {
	return {
		id: '29r928e892e',
		name: 'Role',
		restaurant: makeRestaurantStub(),
		access: {
			id: '32423reretretert',
			createRestaurants: false,
			createUsers: false,
			createProducts: false,
			createCategories: false,
			createIngredients: false,
			createOrders: false,
			createRoles: false,
			createTables: false,
			readRestaurants: false,
			readUsers: false,
			readProducts: false,
			readCategories: false,
			readIngredients: false,
			readOrders: false,
			readRoles: false,
			readTables: false,
			updateRestaurants: false,
			updateUsers: false,
			updateProducts: false,
			updateCategories: false,
			updateIngredients: false,
			updateOrders: false,
			updateRoles: false,
			updateTables: false,
			deleteRestaurants: false,
			deleteUsers: false,
			deleteProducts: false,
			deleteCategories: false,
			deleteIngredients: false,
			deleteOrders: false,
			deleteRoles: false,
			deleteTables: false,
			defineAccess: false,
		},
		createdAt: '',
		updatedAt: '',
	};
}
